CREATE TABLE GBIF_export (
  data_provider_id integer NOT NULL,
  data_resource_id integer NOT NULL,
  Data_provider varchar(255) default NULL,
  Dataset varchar(255) default NULL,
  Collector_name varchar(255) default NULL,
  Date_collected varchar(50) default NULL,
  Institution_code varchar(255) default NULL,
  Collection_code varchar(255) default NULL,
  Catalogue_number varchar(255) default NULL,
  Basis_of_record varchar(100) default NULL,
  last_indexed timestamp NULL default NULL,
  Identifier varchar(255) default NULL,
  Identification_date timestamp default NULL,
  Scientific_name_original varchar(255) default NULL,
  Author varchar(255) default NULL,
  Scientific_name varchar(255) NOT NULL,
  Kingdom varchar(255),
  Phylum varchar(255),
  Class varchar(255),
  Order_rank varchar(255),
  Genus varchar(255),
  Country char(2) default NULL,
  Locality text,
  County varchar(100) default NULL,
  Continent_or_Ocean varchar(100) default NULL,
  State_Province varchar(100) default NULL,
  Region char(3) default NULL,
  Provider_country char(2) default NULL,
  Latitude varchar(50) default NULL,
  Longitude varchar(50) default NULL,
  Coordinate_precision varchar(50) default NULL,
  geospatial_issue integer default NULL,
  cell_id integer default NULL,
  centi_cell_id integer default NULL,
  Min_depth varchar(50) default NULL,
  Max_depth varchar(50) default NULL,
  Min_altitude varchar(50) default NULL,
  Max_altitude varchar(50) default NULL,
  Altitude_precision varchar(50) default NULL,
  gbif_portal_url text NOT NULL default '',
  gbif_webservice_url text NOT NULL default '',
  occurrence_id integer NOT NULL,
  nub_concept_id integer default NULL
) ;

COPY GBIF_export FROM '/home/aheugheb/db/BDP/standard_dump_BELGIUMa_20111116.txt' NULL AS E'\\N' DELIMITER E'\t';
COPY GBIF_export FROM '/home/aheugheb/db/BDP/standard_dump_BELGIUMb_20111116.txt' NULL AS E'\\N' DELIMITER E'\t';


